# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/forms/evEditor.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EVEditor(object):
    def setupUi(self, EVEditor):
        EVEditor.setObjectName("EVEditor")
        EVEditor.resize(700, 386)
        self.centralwidget = QtWidgets.QWidget(EVEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_2.addWidget(self.removeButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.evTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.evTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.evTableWidget.setDragDropOverwriteMode(False)
        self.evTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.evTableWidget.setWordWrap(True)
        self.evTableWidget.setColumnCount(2)
        self.evTableWidget.setObjectName("evTableWidget")
        self.evTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.evTableWidget, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        EVEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EVEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        EVEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EVEditor)
        self.statusbar.setObjectName("statusbar")
        EVEditor.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(EVEditor)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_Qt = QtWidgets.QAction(EVEditor)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout = QtWidgets.QAction(EVEditor)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(EVEditor)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(EVEditor)
        QtCore.QMetaObject.connectSlotsByName(EVEditor)

    def retranslateUi(self, EVEditor):
        _translate = QtCore.QCoreApplication.translate
        EVEditor.setWindowTitle(_translate("EVEditor", "EVEditor"))
        self.addButton.setText(_translate("EVEditor", "Add"))
        self.removeButton.setText(_translate("EVEditor", "Remove"))
        self.evTableWidget.setSortingEnabled(True)
        self.saveButton.setText(_translate("EVEditor", "Save"))
        self.exitButton.setText(_translate("EVEditor", "Exit"))
        self.menuFile.setTitle(_translate("EVEditor", "File"))
        self.menuAbout.setTitle(_translate("EVEditor", "About"))
        self.actionQuit.setText(_translate("EVEditor", "Quit"))
        self.actionAbout_Qt.setText(_translate("EVEditor", "About Qt"))
        self.actionAbout.setText(_translate("EVEditor", "About"))
        self.actionSave.setText(_translate("EVEditor", "Save"))

